{
 "title": "Apache Camel Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(camel_exchanges_total,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(camel_routes_running_routes{eventType=\"RouteEvent\", cluster=~\"$cluster\", node=~\"$node\"},namespace)"
    }
   },
   {
    "name": "context",
    "label": "Camel Context",
    "query": {
     "query": "label_values(camel_routes_running_routes{eventType=\"RouteEvent\", namespace=\"$namespace\", cluster=~\"$cluster\", node=~\"$node\"},camelContext)"
    }
   },
   {
    "name": "route",
    "label": "Camel Route",
    "query": {
     "query": "label_values(camel_exchanges_succeeded_total{camelContext=~\"$context\", cluster=~\"$cluster\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"},routeId)"
    }
   },
   {
    "name": "app_name",
    "label": "Name",
    "query": {
     "query": "label_values(camel_routes_running_routes{eventType=\"RouteEvent\",camelContext=\"$context\"},app_kubernetes_io_name)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(camel_exchanges_total{cluster=~\"$cluster\", node=~\"$node\", namespace=~\"$namespace\"},pod)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(camel_exchanges_total{cluster=~\"$cluster\"},node)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://camel.apache.org/_/img/logo-d-a567cee6fa.svg\" height=\"90%\" width=\"90%\"/>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 20, "x": 2, "y": 0 },
   "options": {
    "content": "<p style=\"padding-top: 30px;color:#e97826;font-size:300%;font-weight:bold\">Camel Monitoring Dashboard</p>"
   }
  },
  {
   "title": "Global Stats Camel Context : $context",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Routes Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (\n    camel_routes_running_routes{\n        cluster=~\"$cluster\",\n        namespace=~\"$namespace\",\n        camelContext=~\"$context\",\n        app_kubernetes_io_name=~\"$app_name\",\n        node=~\"$node\",\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n    }\n)",
     "legendFormat": "Instances"
    },
    {
     "expr": "sum(\n    camel_routes_running_routes{\n        cluster=~\"$cluster\",\n        namespace=~\"$namespace\",\n        camelContext=~\"$context\",\n        app_kubernetes_io_name=~\"$app_name\",\n        node=~\"$node\",\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n    }\n) \n/ \nsum(\n    camel_routes_added_routes{\n        cluster=~\"$cluster\",\n        namespace=~\"$namespace\",\n        camelContext=~\"$context\",\n        app_kubernetes_io_name=~\"$app_name\",\n        node=~\"$node\",\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n    }\n)\n*\n100",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(\n    camel_routes_added_routes{\n        cluster=~\"$cluster\",\n        namespace=~\"$namespace\",\n        camelContext=~\"$context\",\n        app_kubernetes_io_name=~\"$app_name\",\n        node=~\"$node\",\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n    }\n)",
     "legendFormat": "Routes"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "description": "Shows completed exchanges of the camel context in the time range",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    increase(\n        camel_exchanges_total{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            camelContext=~\"$context\",\n            routeId=~\"$route\",\n            app_kubernetes_io_name=~\"$app_name\"\n        }[$__range]\n    )\n)"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (camelContext) (\n    increase(\n        camel_exchanges_failed_total{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            camelContext=\"$context\",\n            routeId=~\"$route\",\n            app_kubernetes_io_name=~\"$app_name\",\n        }[$__range]\n    )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (camelContext) (\n    increase(\n        camel_exchanges_failed_total{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            camelContext=\"$context\",\n            routeId=~\"$route\",\n            app_kubernetes_io_name=~\"$app_name\",\n        }[$__range])\n    ) \n/ \nsum by (camelContext) (\n    increase(\n        camel_exchanges_total{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            camelContext=\"$context\",\n            routeId=~\"$route\",\n            app_kubernetes_io_name=~\"$app_name\",\n        }[$__range]\n    )\n)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation : CPU Usage by node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(node) (\n    process_cpu_usage{\n        cluster=~\"$cluster\",\n        node=~\"$node\",\n        namespace=~\"$namespace\",\n        pod=~\"$pod\",\n    }\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Saturation : Memory usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n    jvm_memory_used_bytes{\n        cluster=~\"$cluster\",\n        node=~\"$node\",\n        namespace=~\"$namespace\",\n        pod=~\"$pod\",\n        area=\"heap\"\n    }\n) \n/ \nsum by (pod) (\n    jvm_memory_max_bytes{\n        cluster=~\"$cluster\",\n        node=~\"$node\",\n        namespace=~\"$namespace\",\n        pod=~\"$pod\",\n        area=\"heap\"\n    }\n)",
     "legendFormat": "{{pod}} heap"
    },
    {
     "expr": "sum by (pod) (\n    jvm_memory_used_bytes{\n        cluster=~\"$cluster\",\n        node=~\"$node\",\n        namespace=~\"$namespace\",\n        pod=~\"$pod\",\n        area=\"nonheap\"\n    }\n) \n/ \nsum by (pod) (\n    jvm_memory_max_bytes{\n        cluster=~\"$cluster\",\n        node=~\"$node\",\n        namespace=~\"$namespace\",\n        pod=~\"$pod\",\n        area=\"nonheap\"\n    }\n)",
     "legendFormat": "{{pod}} nonheap"
    }
   ]
  },
  {
   "title": "Counters",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(simple_counter_total{\n        cluster=~\"$cluster\",\n        namespace=~\"$namespace\",\n        camelContext=~\"$context\",\n        app_kubernetes_io_name=~\"$app_name\",\n        node=~\"$node\",\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n})",
     "legendFormat": "{{Simple Counter}}"
    },
    {
     "expr": "sum(dummy_call_counter_total{\n        cluster=~\"$cluster\",\n        namespace=~\"$namespace\",\n        camelContext=~\"$context\",\n        app_kubernetes_io_name=~\"$app_name\",\n        node=~\"$node\",\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n})",
     "legendFormat": "{{Dummy API  Counter}}"
    }
   ]
  },
  {
   "title": "Inflight",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    camel_exchanges_inflight{\n        cluster=~\"$cluster\",\n        node=~\"$node\",\n        namespace=~\"$namespace\",\n        pod=~\"$pod\",\n        routeId=~\"$route\",\n        camelContext=~\"$context\",\n        app_kubernetes_io_name=~\"$app_name\"\n    }\n)"
    }
   ]
  },
  {
   "title": "Camel Context Overview - RED (Rate - Errors - Duration)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Rate : Executions / sec",
   "type": "stat",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(routeId) (irate(camel_exchanges_total{camelContext=\"$context\", routeId=~\"$route\"}[$__interval]))",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Duration : Avg Execution time",
   "type": "stat",
   "gridPos": { "h": 13, "w": 9, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (routeId) (\n    increase (\n        camel_route_policy_seconds_sum{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            routeId=~\"$route\",\n            camelContext=~\"$context\"\n        }[$__range]\n    )\n) \n/ \nsum by (routeId) (\n    increase (\n        camel_route_policy_seconds_count{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            routeId=~\"$route\",\n            camelContext=~\"$context\",\n            app_kubernetes_io_name=~\"$app_name\"\n        }[$__range]\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors : Failure Rates",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (routeId) (\n    increase(\n        camel_exchanges_failed_total{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            routeId=~\"$route\",\n            camelContext=~\"$context\",\n            app_kubernetes_io_name=~\"$app_name\"\n        }[$__range]\n    )\n) \n/ \nsum by (routeId) (\n    increase(\n        camel_exchanges_total{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            routeId=~\"$route\",\n            camelContext=~\"$context\",\n            app_kubernetes_io_name=~\"$app_name\"\n        }[$__range]\n    ) > 0\n)",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Traffic Per Route",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ex/sec",
   "type": "stat",
   "description": "Show the numbers of exchanges per second for camel route $route",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 26 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n    irate(\n        camel_exchanges_total{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            routeId=~\"$route\",\n            camelContext=~\"$context\",\n            app_kubernetes_io_name=~\"$app_name\"\n        }[$__rate_interval]\n    )\n)"
    }
   ]
  },
  {
   "title": "$route Exchanges/sec - all instances",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 2, "y": 26 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (camelContext) (\n    irate(\n        camel_exchanges_total{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            routeId=~\"$route\",\n            camelContext=~\"$context\",\n            app_kubernetes_io_name=~\"$app_name\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$route  Exchanges/sec - per instances",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 26 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n    irate(\n        camel_exchanges_total{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            routeId=~\"$route\",\n            camelContext=~\"$context\",\n            app_kubernetes_io_name=~\"$app_name\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$route Failure % - all instances",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 26 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (routeId) (\n    increase(\n        camel_exchanges_failed_total{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            routeId=~\"$route\",\n            camelContext=~\"$context\",\n            app_kubernetes_io_name=~\"$app_name\"\n        }[$__range]\n    )\n) \n/ \nsum by (routeId) (\n    increase(\n        camel_exchanges_total{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            routeId=~\"$route\",\n            camelContext=~\"$context\",\n            app_kubernetes_io_name=~\"$app_name\"\n        }[$__range]\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inflight $route",
   "type": "stat",
   "description": "Current number of inflight exchanges",
   "gridPos": { "h": 5, "w": 2, "x": 17, "y": 26 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (camelContext) (\n    camel_exchanges_inflight{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            routeId=~\"$route\",\n            camelContext=~\"$context\",\n            app_kubernetes_io_name=~\"$app_name\"\n    }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$route Inflight  - per instances",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 26 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (camel_exchanges_inflight{            \n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            routeId=~\"$route\",\n            camelContext=~\"$context\",\n            app_kubernetes_io_name=~\"$app_name\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Execution Times Per Route",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg Exec time $route",
   "type": "stat",
   "description": "Average execution time for a route",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 42 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (camelContext) (\n    increase (\n        camel_route_policy_seconds_sum{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            routeId=~\"$route\",\n            camelContext=~\"$context\",\n            app_kubernetes_io_name=~\"$app_name\"\n        }[$__range]\n    )\n) \n\n/ \n\nsum by (camelContext) (\n    increase (\n        camel_route_policy_seconds_count{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            routeId=~\"$route\",\n            camelContext=~\"$context\",\n            app_kubernetes_io_name=~\"$app_name\"\n        }[$__range]\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Exec time $route - all instances",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 2, "y": 42 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (camelContext) (\n    increase (\n        camel_route_policy_seconds_sum{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            routeId=~\"$route\",\n            camelContext=~\"$context\",\n            app_kubernetes_io_name=~\"$app_name\"\n        }[$__range]\n    )\n) \n \n/ \n \nsum by (camelContext) (\n    increase (\n        camel_route_policy_seconds_count{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            routeId=~\"$route\",\n            camelContext=~\"$context\",\n            app_kubernetes_io_name=~\"$app_name\"\n        }[$__range]\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Exec time $route - per instances",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 42 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n    increase (\n        camel_route_policy_seconds_sum{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            routeId=~\"$route\",\n            camelContext=~\"$context\",\n            app_kubernetes_io_name=~\"$app_name\"\n        }[$__range]\n    )\n) \n \n/ \n \nsum by (pod) (\n    increase (\n        camel_route_policy_seconds_count{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            routeId=~\"$route\",\n            camelContext=~\"$context\",\n            app_kubernetes_io_name=~\"$app_name\"\n        }[$__range]\n    )\n)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Processor Execution Times - $route",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
   "repeat": "route",
   "targets": [
    {
     "expr": "sum by (routeId,nodeId) (\n    increase (\n        camel_message_history_seconds_sum{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            camelContext=~\"$context\",\n            routeId=\"$route\",\n            }[$__range]\n    )\n) \n/ \nsum by (routeId,nodeId) (\n    increase (\n        camel_message_history_seconds_count{\n            cluster=~\"$cluster\",\n            node=~\"$node\",\n            namespace=~\"$namespace\",\n            pod=~\"$pod\",\n            camelContext=~\"$context\",\n            routeId=\"$route\",\n        }[$__range]\n    )\n)\n"
    }
   ]
  }
 ]
}