apiVersion: 1

datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://host.docker.internal:9090
      editable: false
      jsonData:
        httpMethod: GET
        exemplarTraceIdDestinations:
          - name: trace_id
            url: http://host.docker.internal:16686/api/traces/$${__value.raw}
    - name: Jaeger
      type: jaeger
      access: proxy
      url: http://host.docker.internal:16686
      readOnly: false
      user: ""
      database: ""
      basicAuth: false
      isDefault: false
      jsonData": { }
