version: "3"
services:
    jaeger:
        container_name: camel_observation_jaeger
        image: quay.io/jaegertracing/all-in-one
        extra_hosts: ['host.docker.internal:host-gateway']
        environment:
            - COLLECTOR_OTLP_ENABLED=true
            - METRICS_STORAGE_TYPE=prometheus
            - PROMETHEUS_SERVER_URL=http://host.docker.internal:9090
            - PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR=true
        ports:
            - 4317:4317
            - 4318:4318
            - 16686:16686
            - 14269:14269
    prometheus:
        image: prom/prometheus
        container_name: camel_observation_prometheus
        extra_hosts: ['host.docker.internal:host-gateway']
        command:
            - --enable-feature=exemplar-storage
            - --config.file=/etc/prometheus/prometheus.yml
        volumes:
            - ./docker/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        ports:
            - 9090:9090
    grafana:
        image: grafana/grafana
        container_name: camel_observation_grafana
        extra_hosts: ['host.docker.internal:host-gateway']
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_DISABLE_LOGIN_FORM=true
        volumes:
            - ./docker/config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
            - ./docker/config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
        ports:
            - 3000:3000
# Jaeger: http://localhost:16686/
# Prometheus: http://localhost:9090/
# Grafana: http://localhost:3000/
