spec:
  template:
    spec:
      containers:
      - env:
          - name: JAVA_OPTIONS
            value: " -Dgreeting=@greeting@ "
      livenessProbe:
        httpGet:
          path: /
          port: 8161
          scheme: HTTP
        initialDelaySeconds: 180
      readinessProbe:
        httpGet:
          path: /
          port: 8161
          scheme: HTTP
        initialDelaySeconds: 10